<a href="https://colab.research.google.com/github/Blaze10/DL/blob/main/regularization/regular_dropout_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

## Using dropout

In [3]:
prob = .5
dropout = nn.Dropout(p=prob)
x = torch.ones(10)

y = dropout(x)
print(f'x: {x}')
print(f'y: {y}')
print(y * (1-prob))
print(torch.mean(y))

x: tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
y: tensor([2., 2., 0., 2., 0., 0., 0., 0., 2., 2.])
tensor([1., 1., 0., 1., 0., 0., 0., 0., 1., 1.])
tensor(1.)


In [4]:
# dropout is turned off when evaluating the model
dropout.eval()
y = dropout(x)
print(y)
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor(1.)


In [5]:
# F.dropout() is not deactivated in eval model
dropout.eval()
y = F.dropout(x)
print(y)
print(torch.mean(y))

tensor([0., 0., 0., 2., 0., 0., 2., 0., 0., 0.])
tensor(0.4000)


In [6]:
# for F.dropout() need to manually switch it off
y = F.dropout(x, training=False)
print(y)
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor(1.)
